import React from 'react';
import {createRoot} from 'react-dom/client';
import {motion} from 'framer-motion';
import {FiArrowUpRight,FiMail,FiPhone,FiMapPin,FiMenu} from 'react-icons/fi';
import './styles.css';
const fade={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:.55}}};
const networks=[
 {tag:'PEOPLE SOLUTIONS',title:'CorporateHr Network',copy:'Human resources, recruitment, training, workforce administration and HR technology.',href:'https://corporatehr.crnetwork.com.ng/',cta:'Visit CorporateHr'},
 {tag:'LOGISTICS SOLUTIONS',title:'Corporate Logistics Network',copy:'Logistics coordination, transport support, distribution and practical movement solutions.',href:'#logistics',cta:'Explore Logistics'},
 {tag:'WORKPLACE RESOURCES',title:'Corporate Office Resource & Supplies',copy:'Office resources, procurement support and essential workplace supplies for organisations.',href:'#office',cta:'Explore Office Resources'}
];
function Header(){const[open,setOpen]=React.useState(false);return <header><a className="brand" href="#home"><span>CR</span><div><b>Corporate Resources Network</b><small>ONE NETWORK. MULTIPLE BUSINESS SOLUTIONS.</small></div></a><button onClick={()=>setOpen(!open)} aria-label="Toggle menu"><FiMenu/></button><nav className={open?'open':''}><a href="#networks">Our Networks</a><a href="#about">About</a><a href="#contact">Contact</a><a className="pill" href="https://corporatehr.crnetwork.com.ng/">CorporateHr <FiArrowUpRight/></a></nav></header>}
function App(){return <><Header/><main>
<section id="home" className="hero"><motion.div initial="hidden" animate="show" variants={fade}><span className="eyebrow">CORPORATE RESOURCES NETWORK</span><h1>One network. Multiple business solutions.</h1><p>Corporate Resources Network connects specialist capabilities across people solutions, logistics and workplace resources—giving organisations one dependable network for practical business support.</p><div className="actions"><a className="btn gold" href="#networks">Explore Our Networks</a><a className="btn ghost" href="#contact">Contact CRNetwork</a></div></motion.div><div className="stack"><div><b>01</b><span>People Solutions</span></div><div><b>02</b><span>Logistics Solutions</span></div><div><b>03</b><span>Business Resources</span></div></div></section>
<section className="band"><span>CorporateHr Network</span><span>Corporate Logistics Network</span><span>Corporate Office Resource & Supplies</span></section>
<section id="networks" className="section"><span className="eyebrow darktext">OUR NETWORKS</span><h2>Three specialist networks. One connected organisation.</h2><p className="lead">Focused expertise across people, logistics and workplace resources—connected by one parent organisation.</p><div className="cards">{networks.map((n,i)=><motion.article key={n.title} variants={fade} initial="hidden" whileInView="show" viewport={{once:true}}><span className="tag">{n.tag}</span><h3>{n.title}</h3><p>{n.copy}</p><a href={n.href}>{n.cta} <FiArrowUpRight/></a></motion.article>)}</div></section>
<section id="about" className="section dark"><div className="two"><div><span className="eyebrow">ABOUT CRNETWORK</span><h2>Specialised expertise, connected by one parent organisation.</h2></div><div><p className="lead">Corporate Resources Network provides a connected platform for business support through specialist networks in human resources, logistics and office resources & supplies.</p><p>Our structure allows each network to build deep operational expertise while clients benefit from a single, coordinated relationship across complementary business needs.</p></div></div></section>
<section id="logistics" className="section warm"><span className="eyebrow darktext">CORPORATE LOGISTICS NETWORK</span><h2>Reliable movement. Better operational flow.</h2><div className="mini"><div><b>Transport Coordination</b><p>Structured movement planning for people, goods and operational requirements.</p></div><div><b>Distribution Support</b><p>Practical delivery, routing and supply movement across locations.</p></div><div><b>Operational Logistics</b><p>Responsive logistics support aligned to business operating needs.</p></div></div></section>
<section id="office" className="section"><span className="eyebrow darktext">CORPORATE OFFICE RESOURCE & SUPPLIES</span><h2>Practical resources for productive workplaces.</h2><div className="mini"><div><b>Office Supplies</b><p>Everyday workplace materials and consumables that keep teams productive.</p></div><div><b>Procurement Support</b><p>Coordinated sourcing and purchasing support for organisational requirements.</p></div><div><b>Administrative Resources</b><p>Practical resources that support office operations and workplace effectiveness.</p></div></div></section>
<section className="section green"><span className="eyebrow">FEATURED NETWORK</span><div className="two"><div><h2>CorporateHr Network</h2><p className="lead">Practical HR advisory, outsourcing, recruitment, training and workforce technology—including CHRiS.</p></div><div className="actions"><a className="btn gold" href="https://corporatehr.crnetwork.com.ng/">Visit CorporateHr Network</a><a className="btn ghost lightghost" href="https://www.chris.crnetwork.com.ng/">Explore CHRiS</a></div></div></section>
<section id="contact" className="section contact"><span className="eyebrow darktext">CONTACT CRNETWORK</span><h2>Start with the group. We’ll connect you to the right network.</h2><div className="contact-grid"><a href="mailto:corporatehr@crnetwork.com.ng"><FiMail/>corporatehr@crnetwork.com.ng</a><a href="tel:+2348100206839"><FiPhone/>+234 810 020 6839</a><span><FiMapPin/>72 Aminu Kano Crescent, Wuse 2, FCT-Abuja, Nigeria</span></div></section>
</main><footer><div><b>Corporate Resources Network</b><p>One Network. Multiple Business Solutions.</p></div><div><a href="https://corporatehr.crnetwork.com.ng/">CorporateHr Network</a><a href="https://www.chris.crnetwork.com.ng/">CHRiS</a></div><span>© 2026 Corporate Resources Network</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);